name: Check macOS version

on:
  workflow_dispatch:

jobs:
  check-macos-version:
    runs-on: macos-26

    steps:
      - name: Log macOS version
        run: |
          sw_vers
          uname -a

      - name: Log Xcode apps
        run: |
          ls -d /Applications/Xcode*.app
